
export interface Product {
  id: number;
  name: string;
  category: "necklace" | "earrings" | "bracelet" | "ring" | "brooch" | "set";
  price: number;
  color: string;
  colorLabel: string;
  savedGrams: number;
  image: string;
  description: string;
  material: string;
  length?: string;
  inStock: boolean;
  featured: boolean;
  tags: string[];
}

export const products: Product[] = [
  {
    id: 1,
    name: 'Колье "Гармония"',
    category: "necklace",
    price: 45,
    color: "purple",
    colorLabel: "Фиолетовый",
    savedGrams: 24,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-01-necklace-harmony-ZB3SLuwYKMTGGuH9Q8TWLv.webp",
    description: "Изящное колье из переработанного фиолетового пластика. Каждый элемент вручную отшлифован и собран на серебристой цепочке.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "42 см + 5 см удлинитель",
    inStock: true,
    featured: true,
    tags: ["колье", "фиолетовый", "элегантное"],
  },
  {
    id: 2,
    name: 'Серьги "Капли росы"',
    category: "earrings",
    price: 35,
    color: "blue",
    colorLabel: "Голубой",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-02-earrings-dewdrops-VyXKprLs6cGhPg5YyiwxiG.webp",
    description: "Элегантные серьги в форме капель из голубого переработанного пластика. Легкие и удобные для ежедневного ношения.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: true,
    tags: ["серьги", "голубой", "капли"],
  },
  {
    id: 3,
    name: 'Браслет "Радуга"',
    category: "bracelet",
    price: 40,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 15,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-03-bracelet-rainbow-eddThTHbarU9QpG5rEPkvr.webp",
    description: "Яркий браслет из разноцветных переработанных пластиков. Каждый цвет символизирует надежду на чистую планету.",
    material: "Переработанный пластик разных цветов, серебристая фурнитура",
    inStock: true,
    featured: true,
    tags: ["браслет", "радуга", "мультиколор"],
  },
  {
    id: 4,
    name: 'Кольцо "Минимум"',
    category: "ring",
    price: 25,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 4,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-04-ring-minimum-Df5kcFkGyMKocEDTmw3TDi.webp",
    description: "Минималистичное кольцо из серебристого переработанного пластика. Простой дизайн, максимальный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "серебристый", "минимализм"],
  },
  {
    id: 5,
    name: 'Брошь "Листок"',
    category: "brooch",
    price: 30,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-05-brooch-leaf-dSfV7SgFC4nBKM6TTdAiT9.webp",
    description: "Брошь в форме листка из зелёного переработанного пластика. Символ природы и возрождения.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["брошь", "зелёный", "листок"],
  },
  {
    id: 6,
    name: 'Набор "Летний день"',
    category: "set",
    price: 85,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 28,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-06-set-summer-day-mG4RvHSQLEAF7JQJ5NS6Fu.webp",
    description: "Комплект из серёг, браслета и кольца в летних тонах. Идеально подходит для отпуска и путешествий.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: true,
    tags: ["набор", "летний", "комплект"],
  },
  {
    id: 7,
    name: 'Колье "Звёзды"',
    category: "necklace",
    price: 50,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 20,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-07-necklace-stars-JR9KK9DnVLrsnHY5bae22j.webp",
    description: "Колье с подвесками в форме звёзд из золотистого переработанного пластика. Волшебный и элегантный дизайн.",
    material: "Переработанный пластик, золотистая фурнитура",
    length: "45 см",
    inStock: true,
    featured: false,
    tags: ["колье", "золото", "звёзды"],
  },
  {
    id: 8,
    name: 'Серьги "Геометрия"',
    category: "earrings",
    price: 32,
    color: "black",
    colorLabel: "Чёрный",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-08-earrings-geometry-MM298oXGQTWfXuuhdnKM8d.webp",
    description: "Серьги с геометрическими формами из чёрного переработанного пластика. Смелый и современный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "чёрный", "геометрия"],
  },
  {
    id: 9,
    name: 'Браслет "Волны"',
    category: "bracelet",
    price: 38,
    color: "blue",
    colorLabel: "Голубой",
    savedGrams: 14,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-09-bracelet-waves-MNUCuPmLWsjFzNidpE6hzx.webp",
    description: "Браслет с волнистым рисунком из голубого переработанного пластика. Напоминает морские волны.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "голубой", "волны"],
  },
  {
    id: 10,
    name: 'Кольцо "Цветок"',
    category: "ring",
    price: 28,
    color: "pink",
    colorLabel: "Розовый",
    savedGrams: 5,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-10-ring-flower-UMVJK5AKoFm7ctXeWU8rgz.webp",
    description: "Кольцо в форме цветка из розового переработанного пластика. Нежное и романтичное.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "розовый", "цветок"],
  },
  {
    id: 11,
    name: 'Брошь "Бабочка"',
    category: "brooch",
    price: 32,
    color: "purple",
    colorLabel: "Фиолетовый",
    savedGrams: 9,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-11-brooch-butterfly-bUHUkoadctABR4nv8FriGz.webp",
    description: "Брошь в форме бабочки из фиолетового переработанного пластика. Символ трансформации и красоты.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["брошь", "фиолетовый", "бабочка"],
  },
  {
    id: 12,
    name: 'Набор "Ночь"',
    category: "set",
    price: 95,
    color: "black",
    colorLabel: "Чёрный",
    savedGrams: 32,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-12-set-night-EyLofnGWquX57wELG6NoRi.webp",
    description: "Элегантный чёрный комплект для вечерних выходов. Включает колье, серьги и браслет.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "чёрный", "вечерний"],
  },
  {
    id: 13,
    name: 'Колье "Морская пена"',
    category: "necklace",
    price: 48,
    color: "turquoise",
    colorLabel: "Бирюзовый",
    savedGrams: 22,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-13-necklace-sea-foam-BpZQQX7RdGEzqK5RRiK3SG.webp",
    description: "Колье из бирюзового переработанного пластика с эффектом морской пены. Свежее и летнее.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "40 см",
    inStock: true,
    featured: false,
    tags: ["колье", "бирюзовый", "море"],
  },
  {
    id: 14,
    name: 'Серьги "Солнце"',
    category: "earrings",
    price: 34,
    color: "yellow",
    colorLabel: "Жёлтый",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-14-earrings-sun-cUpGAWDCtbBqfLH5pAQeaK.webp",
    description: "Серьги в форме солнца из жёлтого переработанного пластика. Яркие и позитивные.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "жёлтый", "солнце"],
  },
  {
    id: 15,
    name: 'Браслет "Лес"',
    category: "bracelet",
    price: 39,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 16,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-15-bracelet-forest-Mqxagh88gWGfENGAwSxvwE.webp",
    description: "Браслет из зелёного переработанного пластика с рисунком листьев. Природный и экологичный.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "зелёный", "лес"],
  },
  {
    id: 16,
    name: 'Колье "Океан"',
    category: "necklace",
    price: 52,
    color: "blue",
    colorLabel: "Голубой",
    savedGrams: 25,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-16-necklace-ocean-5wfp7oSJw8ap2M5HwmxXyF.webp",
    description: "Колье с волнистым рисунком из голубого переработанного пластика. Вдохновлено морской тематикой.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "43 см",
    inStock: true,
    featured: false,
    tags: ["колье", "голубой", "море"],
  },
  {
    id: 17,
    name: 'Набор "Весна"',
    category: "set",
    price: 88,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 30,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-17-set-spring-NTqmvLKHh6Xia7caLZnoKr.webp",
    description: "Весенний комплект в зелёных тонах. Символизирует обновление и возрождение природы.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "зелёный", "весна"],
  },
  {
    id: 18,
    name: 'Серьги "Кристалл"',
    category: "earrings",
    price: 36,
    color: "white",
    colorLabel: "Прозрачный",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-18-earrings-crystal-HqyiJW6wcFmzFMMD85g6xr.webp",
    description: "Серьги с кристаллическим блеском из прозрачного переработанного пластика. Элегантные и сияющие.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "прозрачный", "кристалл"],
  },
  {
    id: 19,
    name: 'Браслет "Закат"',
    category: "bracelet",
    price: 42,
    color: "orange",
    colorLabel: "Оранжевый",
    savedGrams: 17,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-19-bracelet-sunset-dp4aBmtytPUcERjN7QiYoE.webp",
    description: "Браслет с градиентом от оранжевого к розовому и фиолетовому. Вдохновлен закатом.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "оранжевый", "закат"],
  },
  {
    id: 20,
    name: 'Кольцо "Корона"',
    category: "ring",
    price: 31,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-20-ring-crown-YZ8YTPdvzbfAYyytodKLS3.webp",
    description: "Кольцо в форме корона из золотистого переработанного пластика. Королевский стиль.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "золото", "корона"],
  },
  {
    id: 21,
    name: 'Колье "Спираль"',
    category: "necklace",
    price: 49,
    color: "purple",
    colorLabel: "Фиолетовый",
    savedGrams: 23,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-21-necklace-spiral-RshcutyJ2wxoGm2fD2qkpg.webp",
    description: "Колье со спиральным рисунком из фиолетового переработанного пластика. Гипнотизирующий дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "44 см",
    inStock: true,
    featured: false,
    tags: ["колье", "фиолетовый", "спираль"],
  },
  {
    id: 22,
    name: 'Серьги "Луна"',
    category: "earrings",
    price: 33,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-22-earrings-moon-QcNeH6gyxUL89nEBCvZ8Qs.webp",
    description: "Серьги в форме луны из серебристого переработанного пластика. Мистический и элегантный дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "серебристый", "луна"],
  },
  {
    id: 23,
    name: 'Браслет "Конфеты"',
    category: "bracelet",
    price: 37,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 13,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-23-bracelet-candy-fQ6jruU85ZusgzW5aSvLYt.webp",
    description: "Браслет с конфетными цветами - розовый, жёлтый и голубой. Весёлый и игривый дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "мультиколор", "конфеты"],
  },
  {
    id: 24,
    name: 'Кольцо "Сердце"',
    category: "ring",
    price: 27,
    color: "red",
    colorLabel: "Красный",
    savedGrams: 5,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-24-ring-heart-8skxqsvMVGP6bfiWBnPhbL.webp",
    description: "Кольцо в форме сердца из красного переработанного пластика. Романтичное и символичное.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "красный", "сердце"],
  },
  {
    id: 25,
    name: 'Набор "Винтаж"',
    category: "set",
    price: 92,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 31,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-25-set-vintage-fRKjEtRvXANpjZotWK6V4H.webp",
    description: "Винтажный комплект с антикварным золотистым финишем. Классический и изысканный стиль.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "золото", "винтаж"],
  },
  {
    id: 26,
    name: 'Колье "Геометрия"',
    category: "necklace",
    price: 47,
    color: "black",
    colorLabel: "Чёрный",
    savedGrams: 21,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-26-necklace-geometric-G2E7Bd6QHpSiekA9wfJH65.webp",
    description: "Колье с геометрическими формами из чёрного переработанного пластика. Современный минимализм.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "41 см",
    inStock: true,
    featured: false,
    tags: ["колье", "чёрный", "геометрия"],
  },
  {
    id: 27,
    name: 'Серьги "Капли"',
    category: "earrings",
    price: 35,
    color: "blue",
    colorLabel: "Голубой",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-27-earrings-drops-Pjzz3N3NbkYwqSnLWTF3L8.webp",
    description: "Серьги в форме капель из голубого переработанного пластика. Текучий и элегантный дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "голубой", "капли"],
  },
  {
    id: 28,
    name: 'Браслет "Горошек"',
    category: "bracelet",
    price: 38,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 14,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-28-bracelet-dots-Retcrkn94gPZi9HJq2hsUE.webp",
    description: "Браслет с горошком из разноцветного переработанного пластика. Весёлый и детский дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "мультиколор", "горошек"],
  },
  {
    id: 29,
    name: 'Кольцо "Спираль"',
    category: "ring",
    price: 26,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 5,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-29-ring-spiral-JEXmprzoRK8TzCrjNe8qVL.webp",
    description: "Кольцо со спиральным узором из серебристого переработанного пластика. Современный дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "серебристый", "спираль"],
  },
  {
    id: 30,
    name: 'Набор "Бохо"',
    category: "set",
    price: 90,
    color: "brown",
    colorLabel: "Коричневый",
    savedGrams: 29,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-30-set-bohemian-DJySiAnc3WTAVGbFGvzTn7.webp",
    description: "Бохо-комплект с естественными земляными тонами. Этнический и природный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "коричневый", "бохо"],
  },
  {
    id: 31,
    name: 'Колье "Абстракция"',
    category: "necklace",
    price: 51,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 24,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-31-necklace-abstract-hdHz5GFoENCUhsQwxGv4we.webp",
    description: "Колье с абстрактными формами в ярких цветах. Современное искусство на вашей шее.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "46 см",
    inStock: true,
    featured: false,
    tags: ["колье", "мультиколор", "абстракция"],
  },
  {
    id: 32,
    name: 'Серьги "Треугольник"',
    category: "earrings",
    price: 34,
    color: "pink",
    colorLabel: "Розовый",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-32-earrings-triangle-eMRHaRy9zJ6VuJVrE4YapZ.webp",
    description: "Серьги в форме треугольника с градиентом от розового к фиолетовому. Геометрический шик.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "розовый", "треугольник"],
  },
  {
    id: 33,
    name: 'Браслет "Полосы"',
    category: "bracelet",
    price: 39,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 15,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-33-bracelet-stripe-F2pPJ3MuoEQQBP4XCLEu4B.webp",
    description: "Браслет с чередующимися полосками разных цветов. Смелый и яркий дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "мультиколор", "полосы"],
  },
  {
    id: 34,
    name: 'Кольцо "Камень"',
    category: "ring",
    price: 29,
    color: "gray",
    colorLabel: "Серый",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-34-ring-stone-3NX6z6LL4nXwEvx36aXX7T.webp",
    description: "Кольцо с текстурой камня из серого переработанного пластика. Природный и грубый стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "серый", "камень"],
  },
  {
    id: 35,
    name: 'Набор "Космос"',
    category: "set",
    price: 96,
    color: "blue",
    colorLabel: "Голубой",
    savedGrams: 33,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-35-set-cosmic-iLnjzN3dkisEdz4RkkPcvn.webp",
    description: "Космический комплект с галактическими узорами в синих и фиолетовых тонах. Волшебный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "голубой", "космос"],
  },
  {
    id: 36,
    name: 'Колье "Мрамор"',
    category: "necklace",
    price: 53,
    color: "black",
    colorLabel: "Чёрный",
    savedGrams: 26,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-36-necklace-marble-XoQGwpeNyM3K4DAfBcZEsM.webp",
    description: "Колье с мраморным узором из чёрного и белого переработанного пластика. Элегантный и классический.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "42 см",
    inStock: true,
    featured: false,
    tags: ["колье", "чёрный", "мрамор"],
  },
  {
    id: 37,
    name: 'Серьги "Шестиугольник"',
    category: "earrings",
    price: 36,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-37-earrings-hexagon-R4pL8DdzD3WzEyodVWSwo8.webp",
    description: "Серьги в форме шестиугольника из золотистого переработанного пластика. Геометрический шик.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "золото", "шестиугольник"],
  },
  {
    id: 38,
    name: 'Браслет "Цепь"',
    category: "bracelet",
    price: 41,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 16,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-38-bracelet-chain-EHDA5dSRfRhBYequvV5TUg.webp",
    description: "Браслет из звеньев серебристого переработанного пластика. Прочный и стильный дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "серебристый", "цепь"],
  },
  {
    id: 39,
    name: 'Кольцо "Лента"',
    category: "ring",
    price: 30,
    color: "rose",
    colorLabel: "Розовое золото",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-39-ring-band-SwZMfyeptPh2sb3tmP6boG.webp",
    description: "Кольцо-лента из розового золота переработанного пластика. Гладкое и полированное.",
    material: "Переработанный пластик, розовое золото",
    inStock: true,
    featured: false,
    tags: ["кольцо", "розовое золото", "лента"],
  },
  {
    id: 40,
    name: 'Набор "Люкс"',
    category: "set",
    price: 99,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 34,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-40-set-luxury-5j7A697EbGAZuWhjUk9cY9.webp",
    description: "Люксовый комплект с премиум-финишем в золотых тонах. Высочайший уровень стиля.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: true,
    tags: ["набор", "золото", "люкс"],
  },
  {
    id: 41,
    name: 'Колье "Жемчуг"',
    category: "necklace",
    price: 55,
    color: "white",
    colorLabel: "Белый",
    savedGrams: 27,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-41-necklace-pearl-DCx2pqHf8yJhmbnVAtso3e.webp",
    description: "Колье с жемчужным блеском из белого переработанного пластика. Элегантное и вневременное.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "40 см",
    inStock: true,
    featured: false,
    tags: ["колье", "белый", "жемчуг"],
  },
  {
    id: 42,
    name: 'Серьги "Овал"',
    category: "earrings",
    price: 37,
    color: "rose",
    colorLabel: "Розовое золото",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-42-earrings-oval-h5C8zW36xaoYsBmWAHkCeR.webp",
    description: "Серьги овальной формы из розового золота переработанного пластика. Классический стиль.",
    material: "Переработанный пластик, розовое золото",
    inStock: true,
    featured: false,
    tags: ["серьги", "розовое золото", "овал"],
  },
  {
    id: 43,
    name: 'Браслет "Бусины"',
    category: "bracelet",
    price: 40,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 15,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-43-bracelet-beaded-k4wDjHRF3mb4gBeTQvpW8x.webp",
    description: "Браслет из разноцветных бусин переработанного пластика. Радостный и весёлый дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "мультиколор", "бусины"],
  },
  {
    id: 44,
    name: 'Кольцо "Твист"',
    category: "ring",
    price: 28,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 5,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-44-ring-twisted-Py8qdCX9hsjzuRWfmXDLDH.webp",
    description: "Кольцо с закрученным узором из серебристого переработанного пластика. Динамичный дизайн.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "серебристый", "твист"],
  },
  {
    id: 45,
    name: 'Набор "Элегант"',
    category: "set",
    price: 93,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 32,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-45-set-elegant-CrKhJkfiYHvPevZkqSz35d.webp",
    description: "Элегантный комплект в серебристых тонах. Утончённый и изысканный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "серебристый", "элегант"],
  },
  {
    id: 46,
    name: 'Колье "Подвеска"',
    category: "necklace",
    price: 50,
    color: "turquoise",
    colorLabel: "Бирюзовый",
    savedGrams: 22,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-46-necklace-pendant-2VbrueK8SBwssqnSdtwSQB.webp",
    description: "Колье с геометрической подвеской из бирюзового переработанного пластика. Современный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "43 см",
    inStock: true,
    featured: false,
    tags: ["колье", "бирюзовый", "подвеска"],
  },
  {
    id: 47,
    name: 'Серьги "Гвоздики"',
    category: "earrings",
    price: 32,
    color: "rose",
    colorLabel: "Розовое золото",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-47-earrings-studs-aiEpUcoLhJKd3X7Hwu7MbY.webp",
    description: "Серьги-гвоздики из розового золота переработанного пластика. Простые и элегантные.",
    material: "Переработанный пластик, розовое золото",
    inStock: true,
    featured: false,
    tags: ["серьги", "розовое золото", "гвоздики"],
  },
  {
    id: 48,
    name: 'Браслет "Звенья"',
    category: "bracelet",
    price: 42,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 17,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-48-bracelet-link-SZLyBdoC7xRmsNmBtqppX6.webp",
    description: "Браслет со звеньями из серебристого переработанного пластика. Прочный и стильный.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "серебристый", "звенья"],
  },
  {
    id: 49,
    name: 'Кольцо "Орнамент"',
    category: "ring",
    price: 31,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-49-ring-ornate-XX3XHc8WcKPV2JvPZFzAaE.webp",
    description: "Кольцо с орнаментом из золотистого переработанного пластика. Декоративное и изысканное.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "золото", "орнамент"],
  },
  {
    id: 50,
    name: 'Набор "Полный"',
    category: "set",
    price: 98,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 35,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/product-50-set-complete-8ZJ7nqb8fPCUsfEsvCBSmN.webp",
    description: "Полный комплект с колье, серьгами, браслетом и кольцом. Всё что нужно для совершенного образа.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: true,
    tags: ["набор", "серебристый", "полный"],
  }
];


export const processSteps = [
  {
    title: "Сбор и сортировка",
    description: "Мы собираем использованный пластик типов 2, 4 и 5. Каждый кусочек тщательно проверяется и сортируется по цвету и типу."
  },
  {
    title: "Очистка",
    description: "Пластик моется и высушивается. Мы удаляем все этикетки и загрязнения, чтобы получить чистый материал."
  },
  {
    title: "Плавление",
    description: "Пластик плавится при контролируемой температуре. Каждый тип имеет свою оптимальную температуру плавления."
  },
  {
    title: "Формирование",
    description: "Расплавленный пластик заливается в формы или вытягивается в нити. Здесь рождается форма будущего украшения."
  },
  {
    title: "Обработка",
    description: "Готовые детали шлифуются, полируются и обрезаются. Каждый элемент доводится до идеального состояния."
  },
  {
    title: "Сборка и упаковка",
    description: "Детали собираются в украшение, проходят финальную проверку качества и упаковываются для отправки."
  }
];

export const faqItems = [
  {
    question: "Из какого пластика вы делаете украшения?",
    answer: "Мы используем только безопасные типы пластика: HDPE (2), PP (5) и LDPE (4). Это пластик из бутылок, контейнеров и упаковки. Мы тщательно проверяем каждую партию."
  },
  {
    question: "Безопасны ли украшения из переработанного пластика?",
    answer: "Да, абсолютно. Мы используем только безопасные типы пластика и плавим их при контролируемой температуре. Все украшения прошли проверку качества и безопасны для ношения."
  },
  {
    question: "Как долго служат украшения?",
    answer: "При правильном уходе украшения из переработанного пластика служат годы. Они не тускнеют, не ломаются и не теряют форму. Просто избегайте прямого солнечного света и экстремальных температур."
  },
  {
    question: "Можно ли вернуть украшение?",
    answer: "Да, у нас есть 30-дневная гарантия возврата. Если украшение не понравилось, верните его в оригинальной упаковке — и мы вернём деньги."
  },
  {
    question: "Как вы доставляете заказы?",
    answer: "Мы предлагаем доставку курьером, самовывоз из мастерской и почтовую доставку. Стоимость доставки зависит от метода и расстояния."
  },
  {
    question: "Есть ли скидки для постоянных клиентов?",
    answer: "Да! Сдавайте нам пластик — за каждые 500г получаете 5% скидку на следующий заказ. Также у нас есть программа лояльности для постоянных покупателей."
  }
];

export const teamMembers = [
  {
    name: "Мария Петрова",
    role: "Основатель и дизайнер",
    bio: "Мария начала собирать пластик в 2019 году. Её мечта — превратить мусор в красоту и вдохновить людей на экологичный образ жизни.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/team-maria-designer.webp"
  },
  {
    name: "Иван Сидоров",
    role: "Главный мастер",
    bio: "Иван работает с пластиком более 10 лет. Его опыт и внимание к деталям делают каждое украшение уникальным произведением искусства.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/team-ivan-master.webp"
  },
  {
    name: "Анна Козлова",
    role: "Координатор проектов",
    bio: "Анна отвечает за каждый заказ и убеждается, что клиент получает лучший сервис. Её энтузиазм заразителен!",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/team-anna-coordinator.webp"
  }
];

export const categories = [
  { id: "necklace", label: "Колье" },
  { id: "earrings", label: "Серьги" },
  { id: "bracelet", label: "Браслеты" },
  { id: "ring", label: "Кольца" },
  { id: "brooch", label: "Броши" },
  { id: "set", label: "Наборы" }
];
