
export interface Product {
  id: number;
  name: string;
  category: "necklace" | "earrings" | "bracelet" | "ring" | "brooch" | "set";
  price: number;
  color: string;
  colorLabel: string;
  savedGrams: number;
  image: string;
  description: string;
  material: string;
  length?: string;
  inStock: boolean;
  featured: boolean;
  tags: string[];
}

export const products: Product[] = [
  {
    id: 1,
    name: 'Колье "Гармония"',
    category: "necklace",
    price: 21,
    color: "purple",
    colorLabel: "Фиолетовый",
    savedGrams: 24,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-harmony-oDyMah6WtiLEeUT3ma76QF.webp",
    description: "Изящное колье из переработанного фиолетового пластика. Каждый элемент вручную отшлифован и собран на серебристой цепочке. Лёгкое, яркое, уникальное.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "42 см + 5 см удлинитель",
    inStock: true,
    featured: true,
    tags: ["колье", "фиолетовый", "листья"],
  },
  {
    id: 2,
    name: 'Серьги "Капли росы"',
    category: "earrings",
    price: 16,
    color: "blue",
    colorLabel: "Голубой",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-drops-blue-KmN3pQ8vWxYz9jL2hR5tS1.webp",
    description: "Элегантные серьги в форме капель из голубого переработанного пластика. Легкие и удобные для ежедневного ношения.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: true,
    tags: ["серьги", "голубой", "капли", "элегантные"],
  },
  {
    id: 3,
    name: 'Браслет "Радуга"',
    category: "bracelet",
    price: 19,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 15,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-rainbow-multicolor-Pq7rT2uVwXyZ8aB3cD4eF5.webp",
    description: "Яркий браслет из разноцветных переработанных пластиков. Каждый цвет символизирует надежду на чистую планету.",
    material: "Переработанный пластик разных цветов, серебристая фурнитура",
    inStock: true,
    featured: true,
    tags: ["браслет", "радуга", "мультиколор", "позитив"],
  },
  {
    id: 4,
    name: 'Кольцо "Минимум"',
    category: "ring",
    price: 12,
    color: "silver",
    colorLabel: "Серебристый",
    savedGrams: 4,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/ring-minimalist-silver-Xy9uV2wXyZa1bC3dE4fG5h.webp",
    description: "Минималистичное кольцо из серебристого переработанного пластика. Простой дизайн, максимальный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "серебристый", "минимализм", "простое"],
  },
  {
    id: 5,
    name: 'Брошь "Листок"',
    category: "brooch",
    price: 14,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/brooch-leaf-green-Zb8vW1xYzA2cD3eF4gH5iJ.webp",
    description: "Брошь в форме листка из зелёного переработанного пластика. Символ природы и возрождения.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["брошь", "зелёный", "листок", "природа"],
  },
  {
    id: 6,
    name: 'Набор "Летний день"',
    category: "set",
    price: 35,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 28,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/set-summer-day-multicolor-Ac4dE5fG6hI7jK8lM9nO0p.webp",
    description: "Комплект из серёг, браслета и кольца в летних тонах. Идеально подходит для отпуска и путешествий.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: true,
    tags: ["набор", "летний", "комплект", "путешествие"],
  },
  {
    id: 7,
    name: 'Колье "Звёзды"',
    category: "necklace",
    price: 28,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 20,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-stars-gold-Bq5rS6tU7vW8xY9zA0bC1d.webp",
    description: "Колье с подвесками в форме звёзд из золотистого переработанного пластика. Волшебный и элегантный дизайн.",
    material: "Переработанный пластик, золотистая фурнитура",
    length: "45 см",
    inStock: true,
    featured: false,
    tags: ["колье", "золото", "звёзды", "волшебное"],
  },
  {
    id: 8,
    name: 'Серьги "Геометрия"',
    category: "earrings",
    price: 17,
    color: "black",
    colorLabel: "Чёрный",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-geometry-black-Cr6sT7uV8wX9yZ0aB1cD2e.webp",
    description: "Серьги с геометрическими формами из чёрного переработанного пластика. Смелый и современный стиль.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "чёрный", "геометрия", "современное"],
  },
  {
    id: 9,
    name: 'Браслет "Волны"',
    category: "bracelet",
    price: 20,
    color: "blue",
    colorLabel: "Голубой",
    savedGrams: 14,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-waves-blue-Ds7tU8vW9xY0zA1bC2dE3f.webp",
    description: "Браслет с волнистым рисунком из голубого переработанного пластика. Напоминает морские волны.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "голубой", "волны", "море"],
  },
  {
    id: 10,
    name: 'Кольцо "Цветок"',
    category: "ring",
    price: 13,
    color: "pink",
    colorLabel: "Розовый",
    savedGrams: 5,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/ring-flower-pink-Et8uV9wX0yZ1aB2cD3eE4f.webp",
    description: "Кольцо в форме цветка из розового переработанного пластика. Нежное и романтичное.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "розовый", "цветок", "романтичное"],
  },
  {
    id: 11,
    name: 'Брошь "Бабочка"',
    category: "brooch",
    price: 15,
    color: "purple",
    colorLabel: "Фиолетовый",
    savedGrams: 9,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/brooch-butterfly-purple-Fu9vW0xY1zZ2aA3bB4cC5d.webp",
    description: "Брошь в форме бабочки из фиолетового переработанного пластика. Символ трансформации и красоты.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["брошь", "фиолетовый", "бабочка", "трансформация"],
  },
  {
    id: 12,
    name: 'Набор "Ночь"',
    category: "set",
    price: 40,
    color: "black",
    colorLabel: "Чёрный",
    savedGrams: 32,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/set-night-black-Gv0wX1yZ2aA3bB4cC5dD6e.webp",
    description: "Элегантный чёрный комплект для вечерних выходов. Включает колье, серьги и браслет.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "чёрный", "вечерний", "элегантный"],
  },
  {
    id: 13,
    name: 'Колье "Морская пена"',
    category: "necklace",
    price: 24,
    color: "turquoise",
    colorLabel: "Бирюзовый",
    savedGrams: 22,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-sea-foam-turquoise-Hw1xY2zZ3aA4bB5cC6dD7e.webp",
    description: "Колье из бирюзового переработанного пластика с эффектом морской пены. Свежее и летнее.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "40 см",
    inStock: true,
    featured: false,
    tags: ["колье", "бирюзовый", "море", "летнее"],
  },
  {
    id: 14,
    name: 'Серьги "Солнце"',
    category: "earrings",
    price: 18,
    color: "yellow",
    colorLabel: "Жёлтый",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-sun-yellow-Ix2yZ3aA4bB5cC6dD7eE8f.webp",
    description: "Серьги в форме солнца из жёлтого переработанного пластика. Яркие и позитивные.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "жёлтый", "солнце", "позитив"],
  },
  {
    id: 15,
    name: 'Браслет "Лес"',
    category: "bracelet",
    price: 21,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 16,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-forest-green-Jy3zZ4aA5bB6cC7dD8eE9f.webp",
    description: "Браслет из зелёного переработанного пластика с рисунком листьев. Природный и экологичный.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "зелёный", "лес", "природа"],
  },
  {
    id: 16,
    name: 'Кольцо "Луна"',
    category: "ring",
    price: 14,
    color: "white",
    colorLabel: "Белый",
    savedGrams: 5,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/ring-moon-white-Kz4aA5bB6cC7dD8eE9fF0g.webp",
    description: "Кольцо в форме луны из белого переработанного пластика. Нежное и мистическое.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "белый", "луна", "мистическое"],
  },
  {
    id: 17,
    name: 'Брошь "Сердце"',
    category: "brooch",
    price: 16,
    color: "red",
    colorLabel: "Красный",
    savedGrams: 10,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/brooch-heart-red-La5bB6cC7dD8eE9fF0gG1h.webp",
    description: "Брошь в форме сердца из красного переработанного пластика. Символ любви к природе.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["брошь", "красный", "сердце", "любовь"],
  },
  {
    id: 18,
    name: 'Набор "Весна"',
    category: "set",
    price: 38,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 30,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/set-spring-green-Mb6cC7dD8eE9fF0gG1hH2i.webp",
    description: "Весенний комплект в зелёных тонах. Символизирует обновление и возрождение природы.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "зелёный", "весна", "обновление"],
  },
  {
    id: 19,
    name: 'Колье "Закат"',
    category: "necklace",
    price: 26,
    color: "orange",
    colorLabel: "Оранжевый",
    savedGrams: 21,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-sunset-orange-Nc7dD8eE9fF0gG1hH2iI3j.webp",
    description: "Колье из оранжевого переработанного пластика. Вдохновлено красотой заката.",
    material: "Переработанный пластик, золотистая фурнитура",
    length: "42 см",
    inStock: true,
    featured: false,
    tags: ["колье", "оранжевый", "закат", "красота"],
  },
  {
    id: 20,
    name: 'Серьги "Капли"',
    category: "earrings",
    price: 15,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-drops-green-Od8eE9fF0gG1hH2iI3jJ4k.webp",
    description: "Серьги-капли из зелёного переработанного пластика. Символизируют чистую воду.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "зелёный", "капли", "вода"],
  },
  {
    id: 21,
    name: 'Браслет "Зигзаг"',
    category: "bracelet",
    price: 18,
    color: "purple",
    colorLabel: "Фиолетовый",
    savedGrams: 13,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-zigzag-purple-Pe9fF0gG1hH2iI3jJ4kK5l.webp",
    description: "Браслет с зигзагообразным рисунком из фиолетового переработанного пластика.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "фиолетовый", "зигзаг", "геометрия"],
  },
  {
    id: 22,
    name: 'Кольцо "Спираль"',
    category: "ring",
    price: 12,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 4,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/ring-spiral-gold-Qf0gG1hH2iI3jJ4kK5lL6m.webp",
    description: "Кольцо со спиральным узором из золотистого переработанного пластика.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольцо", "золото", "спираль", "узор"],
  },
  {
    id: 23,
    name: 'Брошь "Звезда"',
    category: "brooch",
    price: 17,
    color: "yellow",
    colorLabel: "Жёлтый",
    savedGrams: 11,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/brooch-star-yellow-Rg1hH2iI3jJ4kK5lL6mM7n.webp",
    description: "Брошь в форме звезды из жёлтого переработанного пластика. Яркая и заметная.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["брошь", "жёлтый", "звезда", "яркая"],
  },
  {
    id: 24,
    name: 'Набор "Осень"',
    category: "set",
    price: 42,
    color: "orange",
    colorLabel: "Оранжевый",
    savedGrams: 35,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/set-autumn-orange-Sh2iI3jJ4kK5lL6mM7nN8o.webp",
    description: "Осенний комплект в оранжевых и коричневых тонах. Тёплый и уютный.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["набор", "оранжевый", "осень", "тепло"],
  },
  {
    id: 25,
    name: 'Серьги "Минимализм"',
    category: "earrings",
    price: 18,
    color: "pink",
    colorLabel: "Нежно-розовый",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-minimalist-studs-Ck2EJBiiZQW4B2WPvrb6H2.webp",
    description: "Минималистичные серьги-гвоздики из переработанного пластика. Геометрические формы в нежных пастельных тонах. Идеальны для повседневного образа.",
    material: "Переработанный пластик, серебристая фурнитура",
    inStock: true,
    featured: false,
    tags: ["серьги", "розовый", "геометрия", "минимализм"],
  },
  {
    id: 26,
    name: 'Колье "Золотые слои"',
    category: "necklace",
    price: 45,
    color: "gold",
    colorLabel: "Золотой",
    savedGrams: 20,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-layered-gold-XyMVy5CizKZC5bY9HfjLsC.webp",
    description: "Многослойное колье с золотыми акцентами. Каждый слой имеет разную длину, создавая элегантный каскадный эффект.",
    material: "Переработанный пластик, золотистая фурнитура",
    length: "40-50 см",
    inStock: true,
    featured: false,
    tags: ["колье", "золото", "многослойное", "элегантное"],
  },
  {
    id: 27,
    name: 'Браслет "Обёртка"',
    category: "bracelet",
    price: 22,
    color: "brown",
    colorLabel: "Коричневый",
    savedGrams: 12,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-wrap-leather-XGHwA3wkdy2ok4irWzpS8Z.webp",
    description: "Браслет-обёртка из переработанного пластика с имитацией кожи. Богемный стиль с золотыми деталями. Регулируемая длина.",
    material: "Переработанный пластик, золотистая фурнитура",
    inStock: true,
    featured: false,
    tags: ["браслет", "коричневый", "богемный", "кожа"],
  },
  {
    id: 28,
    name: 'Кольца "Трио"',
    category: "ring",
    price: 25,
    color: "multicolor",
    colorLabel: "Мультиколор",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/ring-trio-set-Zn2nnf7yqwDB2bwkiFe6kW.webp",
    description: "Набор из 3 стэкируемых колец в разных цветах. Розовое золото, серебро и жёлтое золото. Минималистичный дизайн.",
    material: "Переработанный пластик, многоцветная фурнитура",
    inStock: true,
    featured: false,
    tags: ["кольца", "набор", "стэкируемые", "мультиколор"],
  },
  {
    id: 29,
    name: 'Колье "Геометрия"',
    category: "necklace",
    price: 38,
    color: "black",
    colorLabel: "Чёрный",
    savedGrams: 18,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-statement-geometric-7k4JgUQziYBG7fAwoS9pTU.webp",
    description: "Смелое геометрическое колье из чёрного переработанного пластика. Крупные угловатые формы в стиле арт-деко. Для смелых образов.",
    material: "Переработанный чёрный пластик, серебристая фурнитура",
    length: "45 см",
    inStock: true,
    featured: false,
    tags: ["колье", "чёрный", "геометрия", "арт-деко"],
  },
];

export const reviews = [
  {
    id: 1,
    author: "Мария К.",
    rating: 5,
    text: "Красивые украшения! Качество отличное, а главное — помогаю планете.",
    approved: true,
  },
  {
    id: 2,
    author: "Елена П.",
    rating: 5,
    text: "Люблю эко-украшения. Вторая жизнь — лучший выбор!",
    approved: true,
  },
  {
    id: 3,
    author: "Анна М.",
    rating: 4,
    text: "Хорошее качество, быстрая доставка. Рекомендую!",
    approved: true,
  },
];

export const teamMembers = [
  {
    name: "Екатерина Дударева",
    role: "Основатель и дизайнер",
    bio: "Екатерина создала Вторую жизнь с целью показать, что переработанный пластик может быть красивым и стильным. Каждое украшение — это её любовь к природе.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/about-team-8xbZE3tBUxja9yvPDvHgJE.webp",
  },
];

export const processSteps = [
  {
    title: "Сбор",
    description: "Мы собираем переработанный пластик из различных источников.",
    icon: "Recycle",
  },
  {
    title: "Сортировка",
    description: "Пластик сортируется по типам и цветам для качественной переработки.",
    icon: "Filter",
  },
  {
    title: "Переработка",
    description: "Пластик переплавляется и формируется в новые материалы.",
    icon: "Zap",
  },
  {
    title: "Дизайн",
    description: "Наши дизайнеры создают уникальные украшения из переработанного материала.",
    icon: "Palette",
  },
  {
    title: "Сборка",
    description: "Каждое украшение собирается вручную с любовью и вниманием к деталям.",
    icon: "Wrench",
  },
  {
    title: "Доставка",
    description: "Готовое украшение упаковывается и отправляется вам с заботой о планете.",
    icon: "Package",
  },
];

export const faqItems = [
  {
    question: "Из чего сделаны украшения?",
    answer: "Все украшения сделаны из переработанного пластика, который мы собираем и трансформируем в красивые изделия. Фурнитура выполнена из серебристого или золотистого металла.",
  },
  {
    question: "Как долго служат украшения?",
    answer: "При правильном уходе украшения служат несколько лет. Рекомендуем избегать контакта с водой и хранить в сухом месте.",
  },
  {
    question: "Куда вы доставляете?",
    answer: "Мы отправляем по всему миру. Доставка бесплатна при заказе от 60 рублей. Время доставки 5-14 дней в зависимости от региона.",
  },
  {
    question: "Можно ли вернуть товар?",
    answer: "Да, в течение 30 дней после покупки вы можете вернуть товар в исходном состоянии и получить полный возврат средств.",
  },
  {
    question: "Сколько пластика спасает каждое украшение?",
    answer: "Каждое украшение спасает от 5 до 30 граммов пластика, в зависимости от размера и типа. Смотрите точное количество на странице каждого товара.",
  },
  {
    question: "Есть ли гарантия на украшения?",
    answer: "Да, мы гарантируем качество всех украшений. Если возникнут проблемы, свяжитесь с нами, и мы решим вопрос.",
  },
];

export const categories = [
  { id: "necklace", label: "Колье", icon: "Necklace" },
  { id: "earrings", label: "Серьги", icon: "Earrings" },
  { id: "bracelet", label: "Браслеты", icon: "Bracelet" },
  { id: "ring", label: "Кольца", icon: "Ring" },
  { id: "brooch", label: "Броши", icon: "Brooch" },
  { id: "set", label: "Наборы", icon: "Package" },
];
