// Product data for 2Life.by jewelry store
// Design: Eco-Minimalism — DM Serif Display + DM Sans, dark green + terracotta palette

export interface Product {
  id: number;
  name: string;
  category: "necklace" | "earrings" | "bracelet" | "ring" | "brooch" | "set";
  price: number;
  color: string;
  colorLabel: string;
  savedGrams: number;
  image: string;
  description: string;
  material: string;
  length?: string;
  inStock: boolean;
  featured: boolean;
  tags: string[];
}

export const products: Product[] = [
  {
    id: 1,
    name: 'Колье "Гармония"',
    category: "necklace",
    price: 21,
    color: "purple",
    colorLabel: "Фиолетовый",
    savedGrams: 24,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-harmony-oDyMah6WtiLEeUT3ma76QF.webp",
    description: "Изящное колье из переработанного фиолетового пластика. Каждый элемент вручную отшлифован и собран на серебристой цепочке. Лёгкое, яркое, уникальное.",
    material: "Переработанный пластик, серебристая фурнитура",
    length: "42 см + 5 см удлинитель",
    inStock: true,
    featured: true,
    tags: ["колье", "фиолетовый", "листья"],
  },
  {
    id: 2,
    name: 'Колье "Сияние"',
    category: "necklace",
    price: 50,
    color: "white",
    colorLabel: "Белый/Жемчуг",
    savedGrams: 15,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-shine-brLeGKibgjLdmXNyuoNoc5.webp",
    description: "Массивное колье из переработанного белого пластика. Округлые элементы создают скульптурный эффект. Идеально для минималистичного образа.",
    material: "Переработанный белый пластик, серебристая фурнитура",
    length: "46 см",
    inStock: true,
    featured: true,
    tags: ["колье", "белый", "минимализм"],
  },
  {
    id: 3,
    name: 'Колье "Поток"',
    category: "necklace",
    price: 29,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 15,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-flow-amUsmPwu8bF7ZSohCmiyAq.webp",
    description: "Колье из кусочков зелёного переработанного пластика, нанизанных на льняной шнур. Напоминает морские камешки — каждый элемент неповторим.",
    material: "Переработанный зелёный пластик, льняной шнур",
    length: "44 см",
    inStock: true,
    featured: true,
    tags: ["колье", "зелёный", "природа"],
  },
  {
    id: 4,
    name: 'Серьги "Лепесток"',
    category: "earrings",
    price: 55,
    color: "yellow",
    colorLabel: "Жёлтый/Янтарь",
    savedGrams: 17,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-petal-QYBwT5MyRt9rWHcWfpSfLK.webp",
    description: "Серьги-подвески из жёлтого и янтарного пластика в форме лепестков. Золотистые крючки. Лёгкие и яркие — как солнечный день.",
    material: "Переработанный жёлтый/янтарный пластик, позолоченная фурнитура",
    length: "Длина подвески 4 см",
    inStock: true,
    featured: true,
    tags: ["серьги", "жёлтый", "цветок"],
  },
  {
    id: 5,
    name: 'Колье "Природа"',
    category: "necklace",
    price: 45,
    color: "cream",
    colorLabel: "Кремовый",
    savedGrams: 16,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-nature-JCTxaqcJnEmAuqGt2WoaCv.webp",
    description: "Нежное колье из кремово-белого пластика. Округлые формы напоминают природные камни. Универсальное украшение для любого образа.",
    material: "Переработанный кремовый пластик, серебристая фурнитура",
    length: "42 см + 5 см удлинитель",
    inStock: true,
    featured: true,
    tags: ["колье", "кремовый", "минимализм"],
  },
  {
    id: 6,
    name: 'Колье "Радуга"',
    category: "necklace",
    price: 43,
    color: "multicolor",
    colorLabel: "Мультицвет",
    savedGrams: 14,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-multicolor-kgBM49eLqYeVQgXGytWWZN.webp",
    description: "Яркое колье из разноцветного переработанного пластика. Красный, синий, жёлтый, зелёный — каждый элемент из разных источников. Настоящая вторая жизнь!",
    material: "Переработанный разноцветный пластик, льняной шнур",
    length: "46 см",
    inStock: true,
    featured: true,
    tags: ["колье", "мультицвет", "яркий"],
  },
  {
    id: 7,
    name: 'Браслет "Океан"',
    category: "bracelet",
    price: 35,
    color: "blue",
    colorLabel: "Синий/Бирюза",
    savedGrams: 12,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-ocean-kk8eRP6HAkGmYJ6rifzjb4.webp",
    description: "Браслет из синего и бирюзового пластика на эластичном шнуре. Вдохновлён морскими волнами. Подходит для большинства размеров запястья.",
    material: "Переработанный синий/бирюзовый пластик, эластичный шнур",
    length: "Универсальный размер",
    inStock: true,
    featured: false,
    tags: ["браслет", "синий", "море"],
  },
  {
    id: 8,
    name: 'Серьги "Диск"',
    category: "earrings",
    price: 28,
    color: "red",
    colorLabel: "Красный/Коралл",
    savedGrams: 10,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-circle-NL9kk5exKsCRMefk5Gbr2j.webp",
    description: "Круглые серьги-диски из переработанного красного и кораллового пластика. Лаконичная форма, яркий цвет. Отличное дополнение к повседневному образу.",
    material: "Переработанный красный/коралловый пластик, серебристая фурнитура",
    length: "Диаметр 3 см",
    inStock: true,
    featured: false,
    tags: ["серьги", "красный", "круглые"],
  },
  {
    id: 9,
    name: 'Колье "Лес"',
    category: "necklace",
    price: 52,
    color: "forest",
    colorLabel: "Тёмно-зелёный/Коричневый",
    savedGrams: 20,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-forest-PGwBUBvH9UgnBkSEvGuRJq.webp",
    description: "Многоуровневое колье из тёмно-зелёного и коричневого пластика. Слоистые капли создают объёмный эффект. Вдохновлено осенним лесом.",
    material: "Переработанный зелёный и коричневый пластик, бронзовая фурнитура",
    length: "44 см",
    inStock: true,
    featured: false,
    tags: ["колье", "зелёный", "коричневый", "осень"],
  },
  // New products
  {
    id: 10,
    name: 'Серьги "Капля"',
    category: "earrings",
    price: 32,
    color: "teal",
    colorLabel: "Бирюзовый/Коралл",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-drops-hTuorRnDPVfpJxA7sqV95b.webp",
    description: "Двухслойные серьги-капли из бирюзового и кораллового пластика. Геометрическая форма, золотые крючки. Яркий акцент в любом образе.",
    material: "Переработанный бирюзовый и коралловый пластик, позолоченная фурнитура",
    length: "Длина подвески 5 см",
    inStock: true,
    featured: true,
    tags: ["серьги", "бирюзовый", "коралловый", "капли"],
  },
  {
    id: 11,
    name: 'Браслет "Мозаика"',
    category: "bracelet",
    price: 38,
    color: "multicolor",
    colorLabel: "Мультицвет",
    savedGrams: 18,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-mosaic-NDJAtnuLyTYMjJK44DBnxX.webp",
    description: "Широкий браслет-мозаика из разноцветных кусочков пластика. Розовый, жёлтый, синий, белый — каждый фрагмент уникален. Яркий и объёмный.",
    material: "Переработанный разноцветный пластик, эластичная основа",
    length: "Универсальный размер",
    inStock: true,
    featured: false,
    tags: ["браслет", "мозаика", "мультицвет"],
  },
  {
    id: 12,
    name: 'Кольцо "Вихрь"',
    category: "ring",
    price: 18,
    color: "green",
    colorLabel: "Зелёный/Белый",
    savedGrams: 5,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/ring-swirl-CnwJcdiDCAghACPTLxcs4W.webp",
    description: "Кольцо с мраморным узором из зелёного и белого пластика. Полированная поверхность, регулируемый размер. Минималистичный акцент на руке.",
    material: "Переработанный зелёный и белый пластик",
    length: "Регулируемый размер",
    inStock: true,
    featured: false,
    tags: ["кольцо", "зелёный", "мрамор"],
  },
  {
    id: 13,
    name: 'Колье "Пастель"',
    category: "necklace",
    price: 47,
    color: "pastel",
    colorLabel: "Пастельный",
    savedGrams: 13,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-pendants-QcYxS4wmN6PTVMcT8GtBp2.webp",
    description: "Нежное колье с геометрическими подвесками из пастельного пластика. Розовый, мятный, сиреневый — весенние оттенки на золотой цепочке.",
    material: "Переработанный пастельный пластик, позолоченная цепочка",
    length: "42 см",
    inStock: true,
    featured: true,
    tags: ["колье", "пастельный", "геометрия"],
  },
  {
    id: 14,
    name: 'Серьги "Кольцо"',
    category: "earrings",
    price: 30,
    color: "amber",
    colorLabel: "Янтарный/Оранжевый",
    savedGrams: 9,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-hoops-aMbLigku7rph3VuXHtBxMf.webp",
    description: "Серьги-кольца из прозрачного янтарного и оранжевого пластика. Эффект стекла, золотые крючки. Лёгкие и элегантные.",
    material: "Переработанный янтарный пластик, позолоченная фурнитура",
    length: "Диаметр 4 см",
    inStock: true,
    featured: false,
    tags: ["серьги", "янтарный", "кольца"],
  },
  {
    id: 15,
    name: 'Брошь "Лист"',
    category: "brooch",
    price: 22,
    color: "green",
    colorLabel: "Зелёный",
    savedGrams: 7,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/brooch-leaf-Pm8eV3Te4xrGZRqN5jrdnt.webp",
    description: "Брошь в форме листа из матового зелёного пластика. Детальная текстура прожилок, серебристая булавка. Природный акцент на пальто или сумке.",
    material: "Переработанный зелёный пластик, серебристая фурнитура",
    length: "Длина 6 см",
    inStock: true,
    featured: false,
    tags: ["брошь", "зелёный", "лист", "природа"],
  },
  {
    id: 16,
    name: 'Колье "Земля"',
    category: "necklace",
    price: 48,
    color: "earth",
    colorLabel: "Терракота/Оливковый",
    savedGrams: 22,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-beads-WbMG7uj9YvaLPgv2TZcFNZ.webp",
    description: "Колье из плоских бусин в земляных тонах: терракота, оливковый, кремовый, коричневый. Регулируемый шнур. Идеально для бохо-образа.",
    material: "Переработанный пластик в земляных тонах, вощёный шнур",
    length: "Регулируемая длина 40–50 см",
    inStock: true,
    featured: false,
    tags: ["колье", "терракота", "оливковый", "бохо"],
  },
  {
    id: 17,
    name: 'Серьги "Квадрат"',
    category: "earrings",
    price: 33,
    color: "blue",
    colorLabel: "Синий/Белый мрамор",
    savedGrams: 11,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-square-ESC77Ah2fJiYwBS3RN8TRe.webp",
    description: "Квадратные серьги с мраморным узором из синего и белого пластика. Графичная форма, золотые крючки. Стильное украшение для офиса и вечера.",
    material: "Переработанный синий и белый пластик, позолоченная фурнитура",
    length: "Размер 3×3 см",
    inStock: true,
    featured: false,
    tags: ["серьги", "синий", "мрамор", "геометрия"],
  },
  {
    id: 18,
    name: 'Браслет "Пузырьки"',
    category: "bracelet",
    price: 27,
    color: "pastel",
    colorLabel: "Пастельный",
    savedGrams: 10,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-chain-gN2CYu7JuNRddhhJhgkcmh.webp",
    description: "Нежный браслет с тремя круглыми подвесками из пастельного пластика на золотой цепочке. Розовый, жёлтый, голубой — весенние оттенки.",
    material: "Переработанный пастельный пластик, позолоченная цепочка",
    length: "16 см + 3 см удлинитель",
    inStock: true,
    featured: false,
    tags: ["браслет", "пастельный", "пузырьки"],
  },
  {
    id: 19,
    name: 'Кулон "Луна"',
    category: "necklace",
    price: 39,
    color: "purple",
    colorLabel: "Фиолетовый/Белый",
    savedGrams: 11,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-pendant-single-JNYZBXYHWYZoi7N3Hnhkic.webp",
    description: "Крупный круглый кулон с мраморным узором из фиолетового и белого пластика на золотой цепочке. Эффектное украшение для особых случаев.",
    material: "Переработанный фиолетовый и белый пластик, позолоченная цепочка",
    length: "42 см",
    inStock: true,
    featured: true,
    tags: ["кулон", "фиолетовый", "мрамор"],
  },
  {
    id: 20,
    name: 'Колье "Винтаж"',
    category: "necklace",
    price: 52,
    color: "beige",
    colorLabel: "Бежевый/Золотой",
    savedGrams: 20,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/necklace-vintage-fBBtvboi7r8uHdsExtcK2G.webp",
    description: "Элегантное колье в винтажном стиле из бежевого и золотистого пластика. Крупные бусины с матовой поверхностью на позолоченной цепочке. Идеально для вечерних выходов.",
    material: "Переработанный бежевый пластик, позолоченная цепочка",
    length: "45 см",
    inStock: true,
    featured: false,
    tags: ["колье", "винтаж", "бежевый"],
  },
  {
    id: 21,
    name: 'Браслет "Минимал"',
    category: "bracelet",
    price: 24,
    color: "grey",
    colorLabel: "Серый/Бежевый",
    savedGrams: 8,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/bracelet-minimalist-URyy853zuJU6fDdFZB7Hou.webp",
    description: "Минималистичный браслет из серого и бежевого пластика с геометрическим дизайном. Лёгкий, удобный, подходит под любой стиль. Идеален для офиса.",
    material: "Переработанный серый и бежевый пластик",
    length: "17 см + 2 см удлинитель",
    inStock: true,
    featured: false,
    tags: ["браслет", "минимализм", "серый"],
  },
  {
    id: 22,
    name: 'Серьги "Радуга"',
    category: "earrings",
    price: 36,
    color: "rainbow",
    colorLabel: "Разноцветные",
    savedGrams: 12,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/earrings-statement-ax8kCa5v4v9ezvgszFCD3j.webp",
    description: "Яркие серьги-подвески с многоуровневым дизайном из разноцветного пластика. Розовый, жёлтый, голубой, зелёный — праздник на ушах! Идеальны для летних вечеринок.",
    material: "Переработанный разноцветный пластик, серебристая фурнитура",
    length: "Длина 6 см",
    inStock: true,
    featured: true,
    tags: ["серьги", "радуга", "разноцветные"],
  },
  {
    id: 23,
    name: 'Кольцо "Волна"',
    category: "ring",
    price: 20,
    color: "teal",
    colorLabel: "Бирюзовый/Белый",
    savedGrams: 6,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/ring-modern-oHLQeHdRcnG4UQ6iVYMqNh.webp",
    description: "Кольцо с волнистым узором из бирюзового и белого пластика. Современный дизайн, удобная посадка, регулируемый размер. Отличный выбор для повседневного ношения.",
    material: "Переработанный бирюзовый и белый пластик",
    length: "Регулируемый размер",
    inStock: true,
    featured: false,
    tags: ["кольцо", "бирюзовый", "волна"],
  },
  {
    id: 24,
    name: 'Брошь "Абстракция"',
    category: "brooch",
    price: 28,
    color: "rainbow",
    colorLabel: "Разноцветная",
    savedGrams: 9,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/brooch-abstract-ZaN6kBNfGwZGRmc2npfszQ.webp",
    description: "Абстрактная брошь из разноцветного пластика с геометрическими элементами. Каждая брошь уникальна благодаря ручной сборке. Украсит пальто, рюкзак или сумку.",
    material: "Переработанный разноцветный пластик, позолоченная булавка",
    length: "Размер 7x8 см",
    inStock: true,
    featured: false,
    tags: ["брошь", "абстракция", "разноцветная"],
  },
];

export const categories = [
  { id: "all", label: "Все украшения" },
  { id: "necklace", label: "Колье" },
  { id: "earrings", label: "Серьги" },
  { id: "bracelet", label: "Браслеты" },
  { id: "ring", label: "Кольца" },
  { id: "brooch", label: "Броши" },
  { id: "set", label: "Наборы" },
];

export const processSteps = [
  {
    step: 1,
    title: "Сбор пластика",
    description: "Мы собираем пластиковые отходы из домов, кафе и офисов Минска. Принимаем пластик от наших клиентов и партнёров.",
    icon: "♻️",
  },
  {
    step: 2,
    title: "Сортировка и мойка",
    description: "Каждый кусочек пластика сортируется по цвету и типу, тщательно моется и проходит контроль качества.",
    icon: "🔍",
  },
  {
    step: 3,
    title: "Дробление",
    description: "Пластик дробится на небольшие фрагменты нужного размера. Это ключевой этап для создания уникальной текстуры украшений.",
    icon: "⚙️",
  },
  {
    step: 4,
    title: "Плавление и формовка",
    description: "Фрагменты плавятся при низкой температуре и прессуются в формы. Никаких токсичных выбросов — только забота о природе.",
    icon: "🔥",
  },
  {
    step: 5,
    title: "Шлифовка и полировка",
    description: "Каждый элемент вручную шлифуется и полируется до идеального состояния. Это самый кропотливый этап.",
    icon: "✨",
  },
  {
    step: 6,
    title: "Сборка украшения",
    description: "Мастер собирает украшение вручную, подбирая элементы по цвету и форме. Каждое изделие — уникально.",
    icon: "💚",
  },
];

export const faqItems = [
  {
    question: "Из какого пластика сделаны украшения?",
    answer: "Мы используем пластик типов HDPE (2) и PP (5) — это самые безопасные виды пластика. Мы не используем ПВХ и другие токсичные материалы. Весь пластик проходит тщательную очистку перед обработкой.",
  },
  {
    question: "Безопасно ли носить украшения из переработанного пластика?",
    answer: "Да, абсолютно безопасно. Мы используем только пищевые типы пластика, которые не выделяют вредных веществ при нормальной температуре. Фурнитура — из гипоаллергенных материалов (нержавеющая сталь или позолота без никеля).",
  },
  {
    question: "Как ухаживать за украшениями?",
    answer: "Украшения из пластика очень просты в уходе: протирайте мягкой влажной тканью. Избегайте длительного контакта с водой, агрессивными химикатами и прямыми солнечными лучами. Храните в прилагаемом мешочке.",
  },
  {
    question: "Можно ли сдать свой пластик для переработки?",
    answer: "Да! Мы принимаем чистый пластик типов 2 и 5 от наших клиентов. Принесите пластик на наш адрес или договоритесь о самовывозе при заказе от 50 рублей. За каждые 500г пластика — скидка 5% на следующий заказ.",
  },
  {
    question: "Как долго прослужат украшения?",
    answer: "При правильном уходе украшения служат годами. Пластик не ржавеет, не темнеет и сохраняет цвет. Фурнитура из нержавеющей стали также очень долговечна.",
  },
  {
    question: "Есть ли у вас подарочная упаковка?",
    answer: "Да! Все украшения упакованы в крафтовые коробочки с тканевым мешочком. При заказе можно добавить подарочную открытку с вашим текстом — бесплатно.",
  },
  {
    question: "Как вы доставляете заказы?",
    answer: "Доставляем по всей Беларуси Белпочтой и СДЭК. По Минску — курьером или самовывозом. Бесплатная доставка при заказе от 60 рублей.",
  },
  {
    question: "Как оформить возврат?",
    answer: "Возврат возможен в течение 14 дней с момента получения, если товар не был в использовании. Напишите нам на почту с номером заказа, и мы оформим возврат в течение 5 рабочих дней.",
  },
];

export interface Review {
  id: number;
  name: string;
  avatar: string;
  rating: number;
  date: string;
  text: string;
  productName?: string;
}

export const reviews: Review[] = [
  {
    id: 1,
    name: "Мария К.",
    avatar: "МК",
    rating: 5,
    date: "12 апреля 2025",
    text: "Заказала колье «Гармония» и просто влюбилась! Качество отличное, упаковка очень красивая. Приятно осознавать, что украшение сделано из переработанного пластика. Буду заказывать ещё!",
    productName: 'Колье "Гармония"',
  },
  {
    id: 2,
    name: "Анастасия В.",
    avatar: "АВ",
    rating: 5,
    date: "3 марта 2025",
    text: "Серьги «Лепесток» — просто чудо! Лёгкие, яркие, необычные. Все подруги спрашивают, где купила. Очень рада, что нашла этот бренд.",
    productName: 'Серьги "Лепесток"',
  },
  {
    id: 3,
    name: "Екатерина Л.",
    avatar: "ЕЛ",
    rating: 5,
    date: "18 февраля 2025",
    text: "Купила браслет «Океан» в подарок маме. Она в восторге! Доставка быстрая, упаковка экологичная — всё продумано до мелочей. Спасибо за такую красоту!",
    productName: 'Браслет "Океан"',
  },
  {
    id: 4,
    name: "Ольга П.",
    avatar: "ОП",
    rating: 4,
    date: "5 января 2025",
    text: "Очень интересная концепция! Украшения действительно уникальные — два одинаковых не найти. Колье «Поток» ношу каждый день. Единственное пожелание — побольше браслетов в ассортименте.",
    productName: 'Колье "Поток"',
  },
  {
    id: 5,
    name: "Дарья С.",
    avatar: "ДС",
    rating: 5,
    date: "20 декабря 2024",
    text: "Заказывала набор в подарок на Новый год. Всё пришло вовремя, упаковано с любовью. Получатель был в полном восторге! Обязательно вернусь за новыми украшениями.",
  },
  {
    id: 6,
    name: "Виктория Н.",
    avatar: "ВН",
    rating: 5,
    date: "8 ноября 2024",
    text: "Брошь «Лист» — настоящее произведение искусства. Детали прожилок просто невероятные. Ношу на пальто, и все обращают внимание. Очень горжусь, что поддерживаю экологичный бренд!",
    productName: 'Брошь "Лист"',
  },
];

export const teamMembers = [
  {
    name: "Екатерина Дударева",
    role: "Основатель и главный мастер",
    bio: "Екатерина основала «Вторую жизнь» в 2021 году после того, как увидела, сколько пластика выбрасывается ежедневно. Имеет образование дизайнера и 8 лет опыта в ювелирном деле.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663568518180/3hUq5UHQuiApEEj6h2u9CY/about-team-8xbZE3tBUxja9yvPDvHgJE.webp",
  },
];
